# Generated by Django 5.2.6 on 2025-09-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_id_daily_task_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='id_daily',
            new_name='is_daily',
        ),
    ]
