# Generated by Django 5.2.6 on 2025-09-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_id_daily_task_is_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
